name: Docs Validation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7

      - name: Install Vale
        run: |
            brew install vale
            sudo apt-get install python-docutils
            sudo pip install rst2html
            vale ls-config

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            vale $file
          done
      
